use_frameworks!

target "TestSwiftyDropbox_iOS" do
    platform :ios, '10.0'
    pod 'SwiftyDropbox', :path => '../'
end

target "TestSwiftyDropbox_macOS" do
    platform :osx, '10.12'
    pod 'SwiftyDropbox', :path => '../'
end
